name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Cache ORAS binary
      uses: actions/cache@v3
      with:
        path: ~/.local/bin/oras
        key: ${{ runner.os }}-oras

    - name: Install ORAS
      run: |
        if ! command -v oras &> /dev/null; then
          mkdir -p ~/.local/bin  # Ensure the directory exists
          curl -sSL https://github.com/deislabs/oras/releases/latest/download/oras_Linux_x86_64.tar.gz | tar xz -C ~/.local/bin
        fi

    - name: Prepare Trivy DB Directory
      run: |
        mkdir -p ~/.cache/trivy/db  # Ensure the cache directory exists

    - name: Download Trivy DB
      run: |
        # Download and extract Trivy DB
        oras pull ghcr.io/aquasecurity/trivy-db:2
        tar -xzf db.tar.gz
        cp trivy.db metadata.json ~/.cache/trivy/db/

    - name: Cache Trivy DB
      uses: actions/cache@v2
      with:
        path: ~/.cache/trivy/db
        key: ${{ runner.os }}-trivy-db-${{ runner.os }}-${{ github.run_id }}

    - name: Install Trivy
      run: |
        sudo apt-get install -y wget apt-transport-https gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install -y trivy

    - name: Build Docker Image
      run: |
        docker pull ubuntu:latest

    - name: Scan Docker Image with Trivy
      run: |
        trivy image --skip-db-update ubuntu:latest
